### ISSUE TITLE
SIGSEGV with Example Code in README

### ISSUE THREAD

**Issue by hasanyasin** [ba0f3/ngxcmod.nim#2]
Hello,

I have just discovered this and the possibility of building apps in Nim and deploying them as Nginx modules is so exciting. Thank you so much for the great work!

I have successfully compiled the module using the example code, but when I start nginx, it keeps crashing with the logs below:

```
019/10/29 21:26:13 [notice] 8#8:  enabled aio threads for link-function module  in /etc/nginx/nginx.conf :124
2019/10/29 21:26:13 [info] 8#8: Init Default Share memory with 1M in /etc/nginx/nginx.conf:124
2019/10/29 21:26:13 [notice] 8#8: using the "epoll" event method
2019/10/29 21:26:13 [notice] 8#8: start worker processes
2019/10/29 21:26:13 [notice] 8#8: start worker process 45
2019/10/29 21:26:13 [notice] 45#45:  enabled aio threads for link-function module
2019/10/29 21:26:13 [info] 45#45: Application /opt/app/hello.so loaded successfully
2019/10/29 21:26:13 [info] 45#45: application initializing
Traceback (most recent call last)
/home/user/.nimble/pkgs/ngxcmod-0.1.2/ngxcmod.nim(41) onInit
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
2019/10/29 21:26:13 [notice] 8#8: signal 17 (SIGCHLD) received from 45
2019/10/29 21:26:13 [notice] 8#8: worker process 45 exited with code 1
2019/10/29 21:26:13 [notice] 8#8: start worker process 51
2019/10/29 21:26:13 [notice] 8#8: signal 29 (SIGIO) received
2019/10/29 21:26:13 [notice] 9#9: gracefully shutting down
2019/10/29 21:26:13 [notice] 9#9: exiting
2019/10/29 21:26:13 [notice] 9#9: exit
```

To prevent the crash, I needed to remove `ctx.log` calls from both onInit and onExit functions. After commenting out those two lines, it works.

Is it possible that ctx is not initialized or somehow not ready when these two functions are called?

Thank you for the library again!

**Comment by hasanyasin** [comment]
I have just realized that in the example under `test/`, these functions have `ContextCycle` as argument, instead of `Context` and logging function is `ctx.cyc_log` instead of `ctx.log`. 

When I changed these two functions accordingly, everything works perfectly.

Is it just that README.md should be corrected?

**Comment by ba0f3** [comment]
My bad, I will update README, thanks!
